#!/bin/bash
cp /home/test/working/inputs.xlsx  /home/test/working/results/inputs.xlsx
cp /home/test/working/read5.py  /home/test/working/results/read5.py
cp /home/test/working/mp9master.py  /home/test/working/results/mp9master.py
cp /home/test/working/stox11.py  /home/test/working/results/stox11.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "1-AAABal"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "122020AAA6040.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "census.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "2-IWM7525"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "census.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "3-IWM7525_50Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M50Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "4-IWM7525_52Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M52Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "5-IWM7525_54Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M54Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "6-IWM7525_56Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M56Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "7-IWM7525_58Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M58Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "8-IWM7525_60Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M60Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "9-IWM7525_62Q"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M62Q.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "10-IWM7525_50U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M50U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "11-IWM7525_52U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M52U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "12-IWM7525_54U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M54U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "13-IWM7525_56U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M56U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "14-IWM7525_58U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M58U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "15-IWM7525_60U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M60U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
cp /home/test/working/mp9master.py /home/test/working/mp9.py
sed -i '30s/^.*/OUTPUTNAME = "16-IWM7525_62U"/' /home/test/working/mp9.py
sed -i '31s/^.*/NPEEP = 1000/' /home/test/working/mp9.py
sed -i '32s/^.*/RUNS = 1000/' /home/test/working/mp9.py
sed -i '33s/^.*/FUNDVAL = 100000000.0/' /home/test/working/mp9.py
sed -i '34s/^.*/FUNDFILE = "IWM_ESG2020_1_19AAABAL.csv"/' /home/test/working/mp9.py
sed -i '35s/^.*/ANNCUM = "CUM"/' /home/test/working/mp9.py
sed -i '36s/^.*/INCOME = 0.05/' /home/test/working/mp9.py
sed -i '37s/^.*/WMFEE = 0.01/' /home/test/working/mp9.py
sed -i '38s/^.*/PREMIUM = 0.0055000000000000005/' /home/test/working/mp9.py
sed -i '39s/^.*/DISCOUNT = 0.03/' /home/test/working/mp9.py
sed -i '40s/^.*/CENSUSFILE = "M62U.json"/' /home/test/working/mp9.py
sed -i '41s/^.*/ASSUMP_LAP = "NEW"/' /home/test/working/mp9.py
sed -i '42s/^.*/ASSUMP_EXP = "NEW"/' /home/test/working/mp9.py
sed -i '43s/^.*/ASSUMP_MOR = "NEW"/' /home/test/working/mp9.py
sed -i '44s/^.*/STOCHASTIC = False/' /home/test/working/mp9.py
sed -i '45s/^.*/DEBUG = False/' /home/test/working/mp9.py
sed -i '46s/^.*/MORTSPREADSHEET = "IAM20122581_2582.xlsx"/' /home/test/working/mp9.py
sed -i '47s/^.*/YEARONEINCOME = 1.0/' /home/test/working/mp9.py
sed -i '48s/^.*/LAPSEUTILIZATION = "Utilization2020_1_26.xlsx"/' /home/test/working/mp9.py
sed -i '49s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '50s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '51s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '52s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '53s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '54s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '55s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '56s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '57s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '58s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '59s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '60s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '61s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '62s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '63s/^.*/# empty line/' /home/test/working/mp9.py
sed -i '64s/^.*/# empty line/' /home/test/working/mp9.py
/home/ubuntu/anaconda3/bin/python /home/test/working/mp9.py
echo "FINISHED" >> /home/test/working/results/output.txt